module.exports = [
  {
    name: "上海",
    pinyin: "shanghai",
    "mapUrl": {cdn: "/static/js/lib/map/province/shanghai.js"}.cdn,
    cityNames: [
      "黄浦区",
      "徐汇区",
      "长宁区",
      "静安区",
      "普陀区",
      "虹口区",
      "杨浦区",
      "闵行区",
      "宝山区",
      "嘉定区",
      "浦东新区",
      "金山区",
      "松江区",
      "青浦区",
      "奉贤区",
      "崇明区"
    ],
    "cities": {
      "浦东新区": "浦东新区",
      "宝山区": "宝山区",
      "闵行区": "闵行区",
      "静安区": "静安区",
      "徐汇区": "徐汇区",
      "长宁区": "长宁区",
      "松江区": "松江区",
      "普陀区": "普陀区",
      "虹口区": "虹口区",
      "黄浦区": "黄浦区",
      "奉贤区": "奉贤区",
      "杨浦区": "杨浦区",
      "青浦区": "青浦区",
      "嘉定区": "嘉定区",
      "金山区": "金山区",
      "崇明区": "崇明区"
    },
    cityPinyin: [
      "huangpuqu",
      "xuhuiqu",
      "changningqu",
      "jinganqu",
      "putuoqu",
      "hongkouqu",
      "yangpuqu",
      "minhangqu",
      "baoshanqu",
      "jiadingqu",
      "pudongxinqu",
      "jinshanqu",
      "songjiangqu",
      "qingpuqu",
      "fengxianqu",
      "chongmingqu"
    ],
    "center": [
      121.472644,
      31.231706
    ]
  },
  {
    "name": "安徽",
    "pinyin": "anhui",
    "mapUrl": {cdn: "/static/js/lib/map/province/anhui.js"}.cdn,
    "cityNames": [
      "合肥市",
      "芜湖市",
      "蚌埠市",
      "淮南市",
      "马鞍山市",
      "淮北市",
      "铜陵市",
      "安庆市",
      "黄山市",
      "滁州市",
      "阜阳市",
      "宿州市",
      "六安市",
      "亳州市",
      "池州市",
      "宣城市"
    ],
    "cities": {
      "合肥": "合肥市",
      "阜阳": "阜阳市",
      "安庆": "安庆市",
      "亳州": "亳州市",
      "马鞍山": "马鞍山市",
      "蚌埠": "蚌埠市",
      "铜陵": "铜陵市",
      "芜湖": "芜湖市",
      "六安": "六安市",
      "宿州": "宿州市",
      "黄山": "黄山市",
      "淮南": "淮南市",
      "宿松": "宿松市",
      "滁州": "滁州市",
      "淮北": "淮北市",
      "池州": "池州市",
      "宣城": "宣城市"
    },
    cityPinyin: [
      "hefeishi",
      "wuhushi",
      "bangbushi",
      "huainanshi",
      "maanshanshi",
      "huaibeishi",
      "tonglingshi",
      "anqingshi",
      "huangshanshi",
      "chuzhoushi",
      "fuyangshi",
      "suzhoushi",
      "liuanshi",
      "bozhoushi",
      "chizhoushi",
      "xuanchengshi"
    ],
    "center": [
      117.283042,
      31.86119
    ]
  },
  {
    name: "澳门",
    pinyin: "aomen",
    cityNames: [
      "花地玛堂区",
      "花王堂区",
      "望德堂区",
      "大堂区",
      "风顺堂区",
      "嘉模堂区",
      "路凼填海区",
      "圣方济各堂区"
    ],
    cityPinyin: [
      "huadimatangqu",
      "huawangtangqu",
      "wangdetangqu",
      "datangqu",
      "fengshuntangqu",
      "jiamotangqu",
      "ludangtianhaiqu",
      "shengfangjigetangqu"
    ],
    "mapUrl": "/static/js/lib/map/province/aomen.js"
  },
  {
    name: "北京",
    pinyin: "beijing",
    "mapUrl": {cdn: "/static/js/lib/map/province/beijing.js"}.cdn,
    cityNames: [
      "东城区",
      "西城区",
      "朝阳区",
      "丰台区",
      "石景山区",
      "海淀区",
      "门头沟区",
      "房山区",
      "通州区",
      "顺义区",
      "昌平区",
      "大兴区",
      "怀柔区",
      "平谷区",
      "密云区",
      "延庆区"
    ],
    "cities": {
      "海淀区": "海淀区",
      "朝阳区": "朝阳区",
      "大兴区": "大兴区",
      "西城区": "西城区",
      "丰台区": "丰台区",
      "通州区": "通州区",
      "昌平区": "昌平区",
      "石景山区": "石景山区",
      "东城区": "东城区",
      "顺义区": "顺义区",
      "房山区": "房山区",
      "门头沟区": "门头沟区",
      "怀柔区": "怀柔区",
      "密云区": "密云区",
      "延庆区": "延庆区",
      "平谷区": "平谷区"
    },
    cityPinyin: [
      "dongchengqu",
      "xichengqu",
      "zhaoyangqu",
      "fengtaiqu",
      "shijingshanqu",
      "haidianqu",
      "mentougouqu",
      "fangshanqu",
      "tongzhouqu",
      "shunyiqu",
      "changpingqu",
      "daxingqu",
      "huairouqu",
      "pingguqu",
      "miyunqu",
      "yanqingqu"
    ],
    "center": [
      116.405285,
      39.904989
    ]
  },
  {
    "name": "重庆",
    "pinyin": "chongqing",
    "mapUrl": {cdn: "/static/js/lib/map/province/chongqing.js"}.cdn,
    "cityNames": [
      "万州区",
      "涪陵区",
      "渝中区",
      "大渡口区",
      "江北区",
      "沙坪坝区",
      "九龙坡区",
      "南岸区",
      "北碚区",
      "綦江区",
      "大足区",
      "渝北区",
      "巴南区",
      "黔江区",
      "长寿区",
      "江津区",
      "合川区",
      "永川区",
      "南川区",
      "璧山区",
      "铜梁区",
      "潼南区",
      "荣昌区",
      "梁平县",
      "城口县",
      "丰都县",
      "垫江县",
      "武隆县",
      "忠县",
      "云阳县",
      "奉节县",
      "巫山县",
      "巫溪县",
      "石柱土家族自治县",
      "秀山土家族苗族自治县",
      "酉阳土家族苗族自治县",
      "彭水苗族土家族自治县",
      "开州区"
    ],
    cityPinyin: [
      "wanzhouqu",
      "fulingqu",
      "yuzhongqu",
      "dadukouqu",
      "jiangbeiqu",
      "shapingbaqu",
      "jiulongpoqu",
      "nananqu",
      "beibeiqu",
      "qijiangqu",
      "dazuqu",
      "yubeiqu",
      "bananqu",
      "qianjiangqu",
      "changshouqu",
      "jiangjinqu",
      "hechuanqu",
      "yongchuanqu",
      "nanchuanqu",
      "bishanqu",
      "tongliangqu",
      "tongnanqu",
      "rongchangqu",
      "liangpingxian",
      "chengkouxian",
      "fengduxian",
      "dianjiangxian",
      "wulongxian",
      "zhongxian",
      "yunyangxian",
      "fengjiexian",
      "wushanxian",
      "wuxixian",
      "shizhutujiazuzizhixian",
      "xiushantujiazumiaozuzizhixian",
      "youyangtujiazumiaozuzizhixian",
      "pengshuimiaozutujiazuzizhixian",
      "kaizhouqu"
    ],
    "cities": {
      "万州区": "万州区",
      "云阳县": "云阳县",
      "开州区": "开州区",
      "忠县": "忠县",
      "江北区": "江北区",
      "渝北区": "渝北区",
      "垫江县": "垫江县",
      "巫溪县": "巫溪县",
      "两江新区": "两江新区",
      "长寿区": "长寿区",
      "石柱县": "石柱县",
      "九龙坡区": "九龙坡区",
      "合川区": "合川区",
      "璧山区": "璧山区",
      "渝中区": "渝中区",
      "大渡口区": "大渡口区",
      "巫山县": "巫山县",
      "奉节县": "奉节县",
      "丰都县": "丰都县",
      "綦江区": "綦江区",
      "大足区": "大足区",
      "江津区": "江津区",
      "永川区": "永川区",
      "南岸区": "南岸区",
      "铜梁区": "铜梁区",
      "潼南区": "潼南区",
      "梁平区": "梁平区",
      "黔江区": "黔江区",
      "荣昌区": "荣昌区",
      "沙坪坝区": "沙坪坝区",
      "涪陵区": "涪陵区",
      "巴南区": "巴南区",
      "城口县": "城口县",
      "秀山县": "秀山县",
      "武隆区": "武隆区"
    },
    "center": [
      106.504962,
      29.533155
    ]
  },
  {
    name: "福建",
    pinyin: "fujian",
    "mapUrl": {cdn: "/static/js/lib/map/province/fujian.js"}.cdn,
    cityNames: [
      "福州市",
      "厦门市",
      "莆田市",
      "三明市",
      "泉州市",
      "漳州市",
      "南平市",
      "龙岩市",
      "宁德市"
    ],
    cityPinyin: [
      "fuzhoushi",
      "shamenshi",
      "putianshi",
      "sanmingshi",
      "quanzhoushi",
      "zhangzhoushi",
      "nanpingshi",
      "longyanshi",
      "ningdeshi"
    ],
    "cities": {
      "福州": "福州市",
      "莆田": "莆田市",
      "泉州": "泉州市",
      "厦门": "厦门市",
      "漳州": "漳州市",
      "三明": "三明市",
      "宁德": "宁德市",
      "南平": "南平市",
      "龙岩": "龙岩市"
    },
    "center": [
      119.306239,
      26.075302
    ]
  },
  {
    "name": "甘肃",
    "pinyin": "gansu",
    "mapUrl": {cdn: "/static/js/lib/map/province/gansu.js"}.cdn,
    "cityNames": [
      "兰州市",
      "嘉峪关市",
      "金昌市",
      "白银市",
      "天水市",
      "武威市",
      "张掖市",
      "平凉市",
      "酒泉市",
      "庆阳市",
      "定西市",
      "陇南市",
      "临夏回族自治州",
      "甘南藏族自治州"
    ],
    cityPinyin: [
      "lanzhoushi",
      "jiayuguanshi",
      "jinchangshi",
      "baiyinshi",
      "tianshuishi",
      "wuweishi",
      "zhangyeshi",
      "pingliangshi",
      "jiuquanshi",
      "qingyangshi",
      "dingxishi",
      "longnanshi",
      "linxiahuizuzizhizhou",
      "gannancangzuzizhizhou"
    ],
    "cities": {
      "兰州": "兰州市",
      "陇南": "陇南市",
      "天水": "天水市",
      "定西": "定西市",
      "临夏": "临夏市",
      "张掖": "张掖市",
      "白银": "白银市",
      "金昌": "金昌市",
      "平凉": "平凉市",
      "甘南": "甘南市"
    },
    "center": [
      103.823557,
      36.058039
    ]
  },
  {
    name: "广东",
    pinyin: "guangdong",
    "mapUrl": {cdn: "/static/js/lib/map/province/guangdong.js"}.cdn,
    cityNames: [
      "广州市",
      "韶关市",
      "深圳市",
      "珠海市",
      "汕头市",
      "佛山市",
      "江门市",
      "湛江市",
      "茂名市",
      "肇庆市",
      "惠州市",
      "梅州市",
      "汕尾市",
      "河源市",
      "阳江市",
      "清远市",
      "东莞市",
      "中山市",
      "潮州市",
      "揭阳市",
      "云浮市"
    ],
    cityPinyin: [
      "guangzhoushi",
      "shaoguanshi",
      "shenzhenshi",
      "zhuhaishi",
      "shantoushi",
      "foshanshi",
      "jiangmenshi",
      "zhanjiangshi",
      "maomingshi",
      "zhaoqingshi",
      "huizhoushi",
      "meizhoushi",
      "shanweishi",
      "heyuanshi",
      "yangjiangshi",
      "qingyuanshi",
      "dongguanshi",
      "zhongshanshi",
      "chaozhoushi",
      "jieyangshi",
      "yunfushi"
    ],
    "cities": {
      "深圳": "深圳市",
      "广州": "广州市",
      "佛山": "佛山市",
      "珠海": "珠海市",
      "东莞": "东莞市",
      "惠州": "惠州市",
      "中山": "中山市",
      "汕头": "汕头市",
      "湛江": "湛江市",
      "阳江": "阳江市",
      "肇庆": "肇庆市",
      "清远": "清远市",
      "揭阳": "揭阳市",
      "梅州": "梅州市",
      "韶关": "韶关市",
      "汕尾": "汕尾市",
      "茂名": "茂名市",
      "江门": "江门市",
      "潮州": "潮州市",
      "河源": "河源市"
    },
    "center": [
      113.280637,
      23.125178
    ]
  },
  {
    name: "广西",
    pinyin: "guangxi",
    "mapUrl": {cdn: "/static/js/lib/map/province/guangxi.js"}.cdn,
    cityNames: [
      "南宁市",
      "柳州市",
      "桂林市",
      "梧州市",
      "北海市",
      "防城港市",
      "钦州市",
      "贵港市",
      "玉林市",
      "百色市",
      "贺州市",
      "河池市",
      "来宾市",
      "崇左市"
    ],
    cityPinyin: [
      "nanningshi",
      "liuzhoushi",
      "guilinshi",
      "wuzhoushi",
      "beihaishi",
      "fangchenggangshi",
      "qinzhoushi",
      "guigangshi",
      "yulinshi",
      "baiseshi",
      "hezhoushi",
      "hechishi",
      "laibinshi",
      "chongzuoshi"
    ],
    "cities": {
      "北海": "北海市",
      "桂林": "桂林市",
      "南宁": "南宁市",
      "柳州": "柳州市",
      "防城港": "防城港市",
      "河池": "河池市",
      "梧州": "梧州市",
      "玉林": "玉林市",
      "百色": "百色市",
      "钦州": "钦州市",
      "贺州": "贺州市"
    },
    "center": [
      108.320004,
      22.82402
    ]
  },
  {
    name: "贵州",
    pinyin: "guizhou",
    "mapUrl": {cdn: "/static/js/lib/map/province/guizhou.js"}.cdn,
    cityNames: [
      "贵阳市",
      "六盘水市",
      "遵义市",
      "安顺市",
      "毕节市",
      "铜仁市",
      "黔西南布依族苗族自治州",
      "黔东南苗族侗族自治州",
      "黔南布依族苗族自治州"
    ],
    cityPinyin: [
      "guiyangshi",
      "liupanshuishi",
      "zunyishi",
      "anshunshi",
      "bijieshi",
      "tongrenshi",
      "qianxinanbuyizumiaozuzizhizhou",
      "qiandongnanmiaozudongzuzizhizhou",
      "qiannanbuyizumiaozuzizhizhou"
    ],
    "cities": {
      "六盘水": "六盘水市",
      "黔南州": "黔南布衣族苗族自治州",
      "贵阳": "贵阳市",
      "遵义": "遵义市",
      "铜仁": "铜仁市",
      "毕节": "毕节市",
      "黔东南州": "黔东南苗族侗族自治州",
      "黔西南州": "黔西南布衣族苗族自治州"
    },
    "center": [
      106.713478,
      26.578343
    ]
  },
  {
    name: "海南",
    pinyin: "hainan",
    "mapUrl": {cdn: "/static/js/lib/map/province/hainan.js"}.cdn,
    cityNames: [
      "海口市",
      "三亚市",
      "三沙市",
      "儋州市",
      "五指山市",
      "琼海市",
      "文昌市",
      "万宁市",
      "东方市",
      "定安县",
      "屯昌县",
      "澄迈县",
      "临高县",
      "白沙黎族自治县",
      "昌江黎族自治县",
      "乐东黎族自治县",
      "陵水黎族自治县",
      "保亭黎族苗族自治县",
      "琼中黎族苗族自治县"
    ],
    cityPinyin: [
      "haikoushi",
      "sanyashi",
      "sanshashi",
      "danzhoushi",
      "wuzhishanshi",
      "qionghaishi",
      "wenchangshi",
      "wanningshi",
      "dongfangshi",
      "dinganxian",
      "tunchangxian",
      "chengmaixian",
      "lingaoxian",
      "baishalizuzizhixian",
      "changjianglizuzizhixian",
      "ledonglizuzizhixian",
      "lingshuilizuzizhixian",
      "baotinglizumiaozuzizhixian",
      "qiongzhonglizumiaozuzizhixian"
    ],
    "cities": {
      "三亚": "三亚市",
      "海口": "海口市",
      "万宁": "万宁市",
      "儋州": "儋州市",
      "琼海": "琼海市",
      "陵水": "陵水黎族自治县",
      "临高": "临高县",
      "澄迈": "澄迈县",
      "东方": "东方市",
      "琼中": "琼中黎族苗族自治县",
      "定安": "定安县",
      "昌江": "昌江黎族自治县",
      "乐东": "乐东黎族自治县"
    },
    "center": [
      110.33119,
      20.031971
    ]
  },
  {
    name: "河北",
    pinyin: "hebei",
    "mapUrl": {cdn: "/static/js/lib/map/province/hebei.js"}.cdn,
    cityNames: [
      "石家庄市",
      "唐山市",
      "秦皇岛市",
      "邯郸市",
      "邢台市",
      "保定市",
      "张家口市",
      "承德市",
      "沧州市",
      "廊坊市",
      "衡水市"
    ],
    cityPinyin: [
      "shijiazhuangshi",
      "tangshanshi",
      "qinhuangdaoshi",
      "handanshi",
      "xingtaishi",
      "baodingshi",
      "zhangjiakoushi",
      "chengdeshi",
      "cangzhoushi",
      "langfangshi",
      "hengshuishi"
    ],
    "cities": {
      "沧州": "沧州市",
      "石家庄": "石家庄市",
      "保定": "保定市",
      "廊坊": "廊坊市",
      "邯郸": "邯郸市",
      "邢台": "邢台市",
      "唐山": "唐山市",
      "张家口": "张家口市",
      "衡水": "衡水市",
      "承德": "承德市",
      "秦皇岛": "秦皇岛市"
    },
    "center": [
      114.502461,
      38.045474
    ]
  },
  {
    name: "黑龙江",
    pinyin: "heilongjiang",
    "mapUrl": {cdn: "/static/js/lib/map/province/heilongjiang.js"}.cdn,
    cityNames: [
      "哈尔滨市",
      "齐齐哈尔市",
      "鸡西市",
      "鹤岗市",
      "双鸭山市",
      "大庆市",
      "伊春市",
      "佳木斯市",
      "七台河市",
      "牡丹江市",
      "黑河市",
      "绥化市",
      "大兴安岭地区"
    ],
    "cities": {
      "哈尔滨": "哈尔滨市",
      "绥化": "绥化市",
      "佳木斯": "佳木斯市",
      "大庆": "大庆市",
      "牡丹江": "牡丹江市",
      "七台河": "七台河市",
      "鸡西": "鸡西市",
      "齐齐哈尔": "齐齐哈尔市",
      "双鸭山": "双鸭山市",
      "大兴安岭": "大兴安岭地区",
      "鹤岗": "鹤岗市"
    },
    cityPinyin: [
      "haerbinshi",
      "qiqihaershi",
      "jixishi",
      "hegangshi",
      "shuangyashanshi",
      "daqingshi",
      "yichunshi",
      "jiamusishi",
      "qitaiheshi",
      "mudanjiangshi",
      "heiheshi",
      "suihuashi",
      "daxinganlingdiqu"
    ],
    "center": [
      126.642464,
      45.756967
    ]
  },
  {
    "name": "河南",
    "pinyin": "henan",
    "mapUrl": {cdn: "/static/js/lib/map/province/henan.js"}.cdn,
    "cityNames": [
      "郑州市",
      "开封市",
      "洛阳市",
      "平顶山市",
      "安阳市",
      "鹤壁市",
      "新乡市",
      "焦作市",
      "濮阳市",
      "许昌市",
      "漯河市",
      "三门峡市",
      "南阳市",
      "商丘市",
      "信阳市",
      "周口市",
      "驻马店市",
      "济源市"
    ],
    cityPinyin: [
      "zhengzhoushi",
      "kaifengshi",
      "luoyangshi",
      "pingdingshanshi",
      "anyangshi",
      "hebishi",
      "xinxiangshi",
      "jiaozuoshi",
      "puyangshi",
      "xuchangshi",
      "luoheshi",
      "sanmenxiashi",
      "nanyangshi",
      "shangqiushi",
      "xinyangshi",
      "zhoukoushi",
      "zhumadianshi",
      "jiyuanshi"
    ],
    "cities": {
      "信阳": "信阳市",
      "南阳": "南阳市",
      "郑州": "郑州市",
      "驻马店": "驻马店市",
      "周口": "周口市",
      "商丘": "商丘市",
      "安阳": "安阳市",
      "新乡": "新乡市",
      "漯河": "漯河市",
      "许昌": "许昌市",
      "平顶山": "平顶山市",
      "开封": "开封市",
      "三门峡": "三门峡市",
      "永城": "永城市",
      "鹤壁": "鹤壁市",
      "洛阳": "洛阳市",
      "濮阳": "濮阳市",
      "焦作": "焦作市",
      "长垣": "长垣市",
      "滑县": "滑县市"
    },
    "center": [
      113.665412,
      34.757975
    ]
  },
  {
    "name": "湖北",
    "pinyin": "hubei",
    "mapUrl": {cdn: "/static/js/lib/map/province/hubei.js"}.cdn,
    "cityNames": [
      "武汉市",
      "黄石市",
      "十堰市",
      "宜昌市",
      "襄阳市",
      "鄂州市",
      "荆门市",
      "孝感市",
      "荆州市",
      "黄冈市",
      "咸宁市",
      "随州市",
      "恩施土家族苗族自治州",
      "仙桃市",
      "潜江市",
      "天门市",
      "神农架林区"
    ],
    cityPinyin: [
      "wuhanshi",
      "huangshishi",
      "shiyanshi",
      "yichangshi",
      "xiangyangshi",
      "ezhoushi",
      "jingmenshi",
      "xiaoganshi",
      "jingzhoushi",
      "huanggangshi",
      "xianningshi",
      "suizhoushi",
      "enshitujiazumiaozuzizhizhou",
      "xiantaoshi",
      "qianjiangshi",
      "tianmenshi",
      "shennongjialinqu"
    ],
    "cities": {
      "武汉": "武汉市",
      "黄冈": "黄冈市",
      "孝感": "孝感市",
      "襄阳": "襄阳市",
      "随州": "随州市",
      "荆州": "荆州市",
      "宜昌": "宜昌市",
      "荆门": "荆门市",
      "鄂州": "鄂州市",
      "黄石": "黄石市",
      "咸宁": "咸宁市",
      "十堰": "十堰市",
      "仙桃": "仙桃市",
      "恩施州": "恩施土家族苗族自治州",
      "天门": "天门市",
      "潜江": "潜江市",
      "神农架林区": "神农架林区"
    },
    "center": [
      114.298572,
      30.584355
    ]
  },
  {
    "name": "湖南",
    "pinyin": "hunan",
    "mapUrl": {cdn: "/static/js/lib/map/province/hunan.js"}.cdn,
    "cityNames": [
      "长沙市",
      "株洲市",
      "湘潭市",
      "衡阳市",
      "邵阳市",
      "岳阳市",
      "常德市",
      "张家界市",
      "益阳市",
      "郴州市",
      "永州市",
      "怀化市",
      "娄底市",
      "湘西土家族苗族自治州"
    ],
    "cities": {
      "长沙": "长沙市",
      "岳阳": "岳阳市",
      "邵阳": "邵阳市",
      "常德": "常德市",
      "怀化": "怀化市",
      "娄底": "娄底市",
      "衡阳": "衡阳市",
      "益阳": "益阳市",
      "株洲": "株洲市",
      "永州": "永州市",
      "湘潭": "湘潭市",
      "郴州": "郴州市",
      "湘西自治州": "湘西土家族苗族自治州",
      "张家界": "张家界市"
    },
    cityPinyin: [
      "changshashi",
      "zhuzhoushi",
      "xiangtanshi",
      "hengyangshi",
      "shaoyangshi",
      "yueyangshi",
      "changdeshi",
      "zhangjiajieshi",
      "yiyangshi",
      "chenzhoushi",
      "yongzhoushi",
      "huaihuashi",
      "loudishi",
      "xiangxitujiazumiaozuzizhizhou"
    ],
    "center": [
      112.982279,
      28.19409
    ]
  },
  {
    "name": "江苏",
    "pinyin": "jiangsu",
    "mapUrl": {cdn: "/static/js/lib/map/province/jiangsu.js"}.cdn,
    "cityNames": [
      "南京市",
      "无锡市",
      "徐州市",
      "常州市",
      "苏州市",
      "南通市",
      "连云港市",
      "淮安市",
      "盐城市",
      "扬州市",
      "镇江市",
      "泰州市",
      "宿迁市"
    ],
    cityPinyin: [
      "nanjingshi",
      "wuxishi",
      "xuzhoushi",
      "changzhoushi",
      "suzhoushi",
      "nantongshi",
      "lianyungangshi",
      "huaianshi",
      "yanchengshi",
      "yangzhoushi",
      "zhenjiangshi",
      "taizhoushi",
      "suqianshi"
    ],
    "cities": {
      "苏州": "苏州市",
      "南京": "南京市",
      "徐州": "徐州市",
      "泰州": "泰州市",
      "常州": "常州市",
      "连云港": "连云港市",
      "无锡": "无锡市",
      "扬州": "扬州市",
      "盐城": "盐城市",
      "南通": "南通市",
      "淮安": "淮安市",
      "宿迁": "宿迁市",
      "镇江": "镇江市"
    },
    "center": [
      118.767413,
      32.041544
    ]
  },
  {
    name: "江西",
    pinyin: "jiangxi",
    "mapUrl": {cdn: "/static/js/lib/map/province/jiangxi.js"}.cdn,
    cityNames: [
      "南昌市",
      "景德镇市",
      "萍乡市",
      "九江市",
      "新余市",
      "鹰潭市",
      "赣州市",
      "吉安市",
      "宜春市",
      "抚州市",
      "上饶市"
    ],
    cityPinyin: [
      "nanchangshi",
      "jingdezhenshi",
      "pingxiangshi",
      "jiujiangshi",
      "xinyushi",
      "yingtanshi",
      "ganzhoushi",
      "jianshi",
      "yichunshi",
      "fuzhoushi",
      "shangraoshi"
    ],
    "cities": {
      "南昌": "南昌市",
      "九江": "九江市",
      "新余": "新余市",
      "赣州": "赣州市",
      "宜春": "宜春市",
      "抚州": "抚州市",
      "上饶": "上饶市",
      "吉安": "吉安市",
      "萍乡": "萍乡市",
      "鹰潭": "鹰潭市",
      "景德镇": "景德镇市"
    },
    "center": [
      115.892151,
      28.676493
    ]
  },
  {
    name: "吉林",
    pinyin: "jilin",
    "mapUrl": {cdn: "/static/js/lib/map/province/jilin.js"}.cdn,
    cityNames: [
      "长春市",
      "吉林市",
      "四平市",
      "辽源市",
      "通化市",
      "白山市",
      "松原市",
      "白城市",
      "延边朝鲜族自治州"
    ],
    "cities": {
      "长春": "长春市",
      "吉林": "吉林市",
      "松原": "松原市",
      "延边": "延边市",
      "四平": "四平市",
      "公主岭": "公主岭市",
      "通化": "通化市",
      "白城": "白城市",
      "辽源": "辽源市",
      "白山": "白山市",
      "延边州": "延边朝鲜族自治州"
    },
    cityPinyin: [
      "changchunshi",
      "jilinshi",
      "sipingshi",
      "liaoyuanshi",
      "tonghuashi",
      "baishanshi",
      "songyuanshi",
      "baichengshi",
      "yanbianzhaoxianzuzizhizhou"
    ],
    "center": [
      125.3245,
      43.886841
    ]
  },
  {
    "name": "辽宁",
    "pinyin": "liaoning",
    "mapUrl": {cdn: "/static/js/lib/map/province/liaoning.js"}.cdn,
    "cityNames": [
      "沈阳市",
      "大连市",
      "鞍山市",
      "抚顺市",
      "本溪市",
      "丹东市",
      "锦州市",
      "营口市",
      "阜新市",
      "辽阳市",
      "盘锦市",
      "铁岭市",
      "朝阳市",
      "葫芦岛市"
    ],
    cityPinyin: [
      "shenyangshi",
      "dalianshi",
      "anshanshi",
      "fushunshi",
      "benxishi",
      "dandongshi",
      "jinzhoushi",
      "yingkoushi",
      "fuxinshi",
      "liaoyangshi",
      "panjinshi",
      "tielingshi",
      "zhaoyangshi",
      "huludaoshi"
    ],
    "cities": {
      "沈阳": "沈阳市",
      "大连": "大连市",
      "盘锦": "盘锦市",
      "锦州": "锦州市",
      "朝阳": "朝阳市",
      "丹东": "丹东市",
      "葫芦岛": "葫芦岛市",
      "本溪": "本溪市",
      "铁岭": "铁岭市",
      "阜新": "阜新市",
      "营口": "营口市",
      "辽阳": "辽阳市",
      "鞍山": "鞍山市"
    },
    "center": [
      123.429096,
      41.796767
    ]
  },
  {
    "name": "内蒙古",
    "pinyin": "neimenggu",
    "mapUrl": {cdn: "/static/js/lib/map/province/neimenggu.js"}.cdn,
    "cityNames": [
      "呼和浩特市",
      "包头市",
      "乌海市",
      "赤峰市",
      "通辽市",
      "鄂尔多斯市",
      "呼伦贝尔市",
      "巴彦淖尔市",
      "乌兰察布市",
      "兴安盟",
      "锡林郭勒盟",
      "阿拉善盟"
    ],
    "cities": {
      "鄂尔多斯": "鄂尔多斯市",
      "包头": "包头市",
      "巴彦淖尔": "巴彦淖尔市",
      "呼和浩特": "呼和浩特市",
      "呼伦贝尔": "呼伦贝尔市",
      "锡林郭勒盟": "锡林郭勒盟",
      "赤峰": "赤峰市",
      "乌兰察布": "乌兰察布市",
      "兴安盟": "兴安盟",
      "通辽": "通辽市",
      "阿拉善盟": "阿拉善盟"
    },
    cityPinyin: [
      "huhehaoteshi",
      "baotoushi",
      "wuhaishi",
      "chifengshi",
      "tongliaoshi",
      "eerduosishi",
      "hulunbeiershi",
      "bayannaoershi",
      "wulanchabushi",
      "xinganmeng",
      "xilinguolemeng",
      "alashanmeng"
    ],
    "center": [
      111.670801,
      40.818311
    ]
  },
  {
    "name": "宁夏",
    "pinyin": "ningxia",
    "mapUrl": {cdn: "/static/js/lib/map/province/ningxia.js"}.cdn,
    "cityNames": [
      "银川市",
      "石嘴山市",
      "吴忠市",
      "固原市",
      "中卫市"
    ],
    cityPinyin: [
      "yinchuanshi",
      "shizuishanshi",
      "wuzhongshi",
      "guyuanshi",
      "zhongweishi"
    ],
    "cities": {
      "银川": "银川市",
      "吴忠": "吴忠市",
      "中卫": "中卫市",
      "固原": "固原市",
      "石嘴山": "石嘴山市",
      "宁东管委会": "宁东管委会"
    },
    "center": [
      106.278179,
      38.46637
    ]
  },
  {
    "name": "青海",
    "pinyin": "qinghai",
    "mapUrl": {cdn: "/static/js/lib/map/province/qinghai.js"}.cdn,
    "cityNames": [
      "西宁市",
      "海东市",
      "海北藏族自治州",
      "黄南藏族自治州",
      "海南藏族自治州",
      "果洛藏族自治州",
      "玉树藏族自治州",
      "海西蒙古族藏族自治州"
    ],
    "cities": {
      "西宁": "西宁市"
    },
    cityPinyin: [
      "xiningshi",
      "haidongshi",
      "haibeicangzuzizhizhou",
      "huangnancangzuzizhizhou",
      "hainancangzuzizhizhou",
      "guoluocangzuzizhizhou",
      "yushucangzuzizhizhou",
      "haiximengguzucangzuzizhizhou"
    ],
    "center": [
      101.778916,
      36.623178
    ]
  },
  {
    "name": "山东",
    "pinyin": "shandong",
    "mapUrl": {cdn: "/static/js/lib/map/province/shandong.js"}.cdn,
    "cityNames": [
      "济南市",
      "青岛市",
      "淄博市",
      "枣庄市",
      "东营市",
      "烟台市",
      "潍坊市",
      "济宁市",
      "泰安市",
      "威海市",
      "日照市",
      "莱芜市",
      "临沂市",
      "德州市",
      "聊城市",
      "滨州市",
      "菏泽市"
    ],
    "cities": {
      "威海": "威海市",
      "临沂": "临沂市",
      "青岛": "青岛市",
      "烟台": "烟台市",
      "济南": "济南市",
      "德州": "德州市",
      "枣庄": "枣庄市",
      "济宁": "济宁市",
      "日照": "日照市",
      "淄博": "淄博市",
      "潍坊": "潍坊市",
      "滨州": "滨州市",
      "聊城": "聊城市",
      "菏泽": "菏泽市",
      "泰安": "泰安市"
    },
    cityPinyin: [
      "jinanshi",
      "qingdaoshi",
      "ziboshi",
      "zaozhuangshi",
      "dongyingshi",
      "yantaishi",
      "weifangshi",
      "jiningshi",
      "taianshi",
      "weihaishi",
      "rizhaoshi",
      "laiwushi",
      "linyishi",
      "dezhoushi",
      "liaochengshi",
      "binzhoushi",
      "hezeshi"
    ],
    "center": [
      117.000923,
      36.675807
    ]
  },
  {
    "name": "山西",
    "pinyin": "shanxi",
    "mapUrl": {cdn: "/static/js/lib/map/province/shanxi.js"}.cdn,
    "cityNames": [
      "太原市",
      "大同市",
      "阳泉市",
      "长治市",
      "晋城市",
      "朔州市",
      "晋中市",
      "运城市",
      "忻州市",
      "临汾市",
      "吕梁市"
    ],
    "cities": {
      "晋中": "晋中市",
      "运城": "运城市",
      "大同": "大同市",
      "吕梁": "吕梁市",
      "太原": "太原市",
      "长治": "长治市",
      "朔州": "朔州市",
      "晋城": "晋城市",
      "阳泉": "阳泉市",
      "临汾": "临汾市",
      "忻州": "忻州市"
    },
    cityPinyin: [
      "taiyuanshi",
      "datongshi",
      "yangquanshi",
      "changzhishi",
      "jinchengshi",
      "shuozhoushi",
      "jinzhongshi",
      "yunchengshi",
      "xinzhoushi",
      "linfenshi",
      "lvliangshi"
    ],
    "center": [
      112.549248,
      37.857014
    ]
  },
  {
    "name": "陕西",
    "pinyin": "shanxi1",
    "mapUrl": {cdn: "/static/js/lib/map/province/shanxi1.js"}.cdn,
    "cityNames": [
      "西安市",
      "铜川市",
      "宝鸡市",
      "咸阳市",
      "渭南市",
      "延安市",
      "汉中市",
      "榆林市",
      "安康市",
      "商洛市"
    ],
    cityPinyin: [
      "xianshi",
      "tongchuanshi",
      "baojishi",
      "xianyangshi",
      "weinanshi",
      "yananshi",
      "hanzhongshi",
      "yulinshi",
      "ankangshi",
      "shangluoshi"
    ],
    "cities": {
      "西安": "西安市",
      "安康": "安康市",
      "汉中": "汉中市",
      "咸阳": "咸阳市",
      "延安": "延安市",
      "宝鸡": "宝鸡市",
      "铜川": "铜川市",
      "渭南": "渭南市",
      "商洛": "商洛市",
      "榆林": "榆林市",
      "韩城": "韩城市"
    },
    "center": [
      108.948024,
      34.263161
    ]
  },
  {
    "name": "四川",
    "pinyin": "sichuan",
    "mapUrl": {cdn: "/static/js/lib/map/province/sichuan.js"}.cdn,
    "cityNames": [
      "成都市",
      "自贡市",
      "攀枝花市",
      "泸州市",
      "德阳市",
      "绵阳市",
      "广元市",
      "遂宁市",
      "内江市",
      "乐山市",
      "南充市",
      "眉山市",
      "宜宾市",
      "广安市",
      "达州市",
      "雅安市",
      "巴中市",
      "资阳市",
      "阿坝藏族羌族自治州",
      "甘孜藏族自治州",
      "凉山彝族自治州"
    ],
    cityPinyin: [
      "chengdushi",
      "zigongshi",
      "panzhihuashi",
      "luzhoushi",
      "deyangshi",
      "mianyangshi",
      "guangyuanshi",
      "suiningshi",
      "neijiangshi",
      "leshanshi",
      "nanchongshi",
      "meishanshi",
      "yibinshi",
      "guanganshi",
      "dazhoushi",
      "yaanshi",
      "bazhongshi",
      "ziyangshi",
      "abacangzuqiangzuzizhizhou",
      "ganzicangzuzizhizhou",
      "liangshanyizuzizhizhou"
    ],
    "cities": {
      "成都": "成都市",
      "广安": "广安市",
      "南充": "南充市",
      "绵阳": "绵阳市",
      "内江": "内江市",
      "达州": "达州市",
      "自贡": "自贡市",
      "巴中": "巴中市",
      "德阳": "德阳市",
      "宜宾": "宜宾市",
      "攀枝花": "攀枝花市",
      "遂宁": "遂宁市",
      "雅安": "雅安市",
      "泸州": "泸州市",
      "甘孜州": "甘孜藏族自治州",
      "凉山州": "凉山彝族自治州",
      "乐山": "乐山市",
      "眉山": "眉山市",
      "资阳": "资阳市",
      "广元": "广元市",
      "阿坝州": "阿坝藏族羌族自治州"
    },
    "center": [
      104.065735,
      30.659462
    ]
  },
  {
    name: "台湾",
    pinyin: "taiwan",
    "mapUrl": {cdn: "/static/js/lib/map/province/taiwan.js"}.cdn,
    cityNames: [
      "高雄市",
      "屏东县",
      "台南市",
      "新竹市",
      "新竹县",
      "宜兰县",
      "基隆市",
      "苗栗县",
      "台北市",
      "新北市",
      "桃园市",
      "彰化县",
      "嘉义县",
      "嘉义市",
      "花莲县",
      "南投县",
      "台中市",
      "云林县",
      "台东县",
      "澎湖县",
      "金门县",
      "连江县",
      "中国属钓鱼岛"
    ],
    cityPinyin: [
      "gaoxiongshi",
      "pingdongxian",
      "tainanshi",
      "xinzhushi",
      "xinzhuxian",
      "yilanxian",
      "jilongshi",
      "miaolixian",
      "taibeishi",
      "xinbeishi",
      "taoyuanshi",
      "zhanghuaxian",
      "jiayixian",
      "jiayishi",
      "hualianxian",
      "nantouxian",
      "taizhongshi",
      "yunlinxian",
      "taidongxian",
      "penghuxian",
      "jinmenxian",
      "lianjiangxian",
      "zhongguoshudiaoyudao"
    ]
  },
  {
    name: "天津",
    pinyin: "tianjin",
    "mapUrl": {cdn: "/static/js/lib/map/province/tianjin.js"}.cdn,
    cityNames: [
      "和平区",
      "河东区",
      "河西区",
      "南开区",
      "河北区",
      "红桥区",
      "东丽区",
      "西青区",
      "津南区",
      "北辰区",
      "武清区",
      "宝坻区",
      "滨海新区",
      "宁河区",
      "静海区",
      "蓟州区"
    ],
    "cities": {
      "河北区": "河北区",
      "河东区": "河东区",
      "外地来津人员": "外地来津人员",
      "河西区": "河西区",
      "和平区": "和平区",
      "宝坻区": "宝坻区",
      "东丽区": "东丽区",
      "西青区": "西青区",
      "滨海新区": "滨海新区",
      "南开区": "南开区",
      "红桥区": "红桥区",
      "宁河区": "宁河区",
      "蓟州区": "蓟州区"
    },
    cityPinyin: [
      "hepingqu",
      "hedongqu",
      "hexiqu",
      "nankaiqu",
      "hebeiqu",
      "hongqiaoqu",
      "dongliqu",
      "xiqingqu",
      "jinnanqu",
      "beichenqu",
      "wuqingqu",
      "baodiqu",
      "binhaixinqu",
      "ninghequ",
      "jinghaiqu",
      "jizhouqu"
    ],
    "center": [
      117.190182,
      39.125596
    ]
  },
  {
    "name": "香港",
    "pinyin": "xianggang",
    "mapUrl": {cdn: "/static/js/lib/map/province/xianggang.js"}.cdn,
    "cityNames": [
      "中西区",
      "湾仔区",
      "东区",
      "南区",
      "油尖旺区",
      "深水埗区",
      "九龙城区",
      "黄大仙区",
      "观塘区",
      "荃湾区",
      "屯门区",
      "元朗区",
      "北区",
      "大埔区",
      "西贡区",
      "沙田区",
      "葵青区",
      "离岛区"
    ],
    cityPinyin: [
      "zhongxiqu",
      "wanziqu",
      "dongqu",
      "nanqu",
      "youjianwangqu",
      "shenshuibuqu",
      "jiulongchengqu",
      "huangdaxianqu",
      "guantangqu",
      "quanwanqu",
      "tunmenqu",
      "yuanlangqu",
      "beiqu",
      "dapuqu",
      "xigongqu",
      "shatianqu",
      "kuiqingqu",
      "lidaoqu"
    ]
  },
  {
    "name": "新疆",
    "pinyin": "xinjiang",
    "mapUrl": {cdn: "/static/js/lib/map/province/xinjiang.js"}.cdn,
    "cityNames": [
      "乌鲁木齐市",
      "克拉玛依市",
      "吐鲁番市",
      "昌吉回族自治州",
      "博尔塔拉蒙古自治州",
      "巴音郭楞蒙古自治州",
      "阿克苏地区",
      "克孜勒苏柯尔克孜自治州",
      "喀什地区",
      "和田地区",
      "伊犁哈萨克自治州",
      "塔城地区",
      "阿勒泰地区",
      "石河子市",
      "阿拉尔市",
      "图木舒克市",
      "五家渠市",
      "北屯市",
      "铁门关市",
      "双河市",
      "可克达拉市",
      "昆玉市",
      "哈密市"
    ],
    "cities": {
      "乌鲁木齐": "乌鲁木齐市",
      "伊犁州": "伊犁哈萨克自治州",
      "吐鲁番": "吐鲁番市",
      "阿克苏": "阿克苏市"
    },
    cityPinyin: [
      "wulumuqishi",
      "kelamayishi",
      "tulufanshi",
      "changjihuizuzizhizhou",
      "boertalamengguzizhizhou",
      "bayinguolengmengguzizhizhou",
      "akesudiqu",
      "kezilesukeerkezizizhizhou",
      "kashidiqu",
      "hetiandiqu",
      "yilihasakezizhizhou",
      "tachengdiqu",
      "aletaidiqu",
      "shihezishi",
      "alaershi",
      "tumushukeshi",
      "wujiaqushi",
      "beitunshi",
      "tiemenguanshi",
      "shuangheshi",
      "kekedalashi",
      "kunyushi",
      "hamishi"
    ],
    "center": [
      87.617733,
      43.792818
    ]
  },
  {
    "name": "西藏",
    "pinyin": "xizang",
    "mapUrl": {cdn: "/static/js/lib/map/province/xizang.js"}.cdn,
    "cityNames": [
      "拉萨市",
      "日喀则市",
      "昌都市",
      "山南市",
      "那曲地区",
      "阿里地区",
      "林芝市",
      "山南市"
    ],
    cityPinyin: [
      "lasashi",
      "rikazeshi",
      "changdushi",
      "shannanshi",
      "naqudiqu",
      "alidiqu",
      "linzhishi",
      "shannanshi"
    ],
    "center": [
      91.132212,
      29.660361
    ]
  },
  {
    "name": "云南",
    "pinyin": "yunnan",
    "mapUrl": {cdn: "/static/js/lib/map/province/yunnan.js"}.cdn,
    "cityNames": [
      "昆明市",
      "曲靖市",
      "玉溪市",
      "保山市",
      "昭通市",
      "丽江市",
      "普洱市",
      "临沧市",
      "楚雄彝族自治州",
      "红河哈尼族彝族自治州",
      "文山壮族苗族自治州",
      "西双版纳傣族自治州",
      "大理白族自治州",
      "德宏傣族景颇族自治州",
      "怒江傈僳族自治州",
      "迪庆藏族自治州"
    ],
    cityPinyin: [
      "kunmingshi",
      "qujingshi",
      "yuxishi",
      "baoshanshi",
      "zhaotongshi",
      "lijiangshi",
      "puershi",
      "lincangshi",
      "chuxiongyizuzizhizhou",
      "honghehanizuyizuzizhizhou",
      "wenshanzhuangzumiaozuzizhizhou",
      "xishuangbannadaizuzizhizhou",
      "dalibaizuzizhizhou",
      "dehongdaizujingpozuzizhizhou",
      "nujianglisuzuzizhizhou",
      "diqingcangzuzizhizhou"
    ],
    "cities": {
      "昆明": "昆明市",
      "西双版纳": "西双版纳傣族自治州",
      "保山": "保山市",
      "玉溪": "玉溪市",
      "丽江": "丽江市",
      "大理": "大理白族自治州",
      "昭通": "昭通市",
      "曲靖": "曲靖市",
      "红河": "红河哈尼族彝族自治州",
      "普洱": "普洱市",
      "德宏": "德宏傣族景颇族自治州",
      "临沧": "临沧市"
    },
    "center": [
      102.712251,
      25.040609
    ]
  },
  {
    "name": "浙江",
    "pinyin": "zhejiang",
    "mapUrl": {cdn: "/static/js/lib/map/province/zhejiang.js"}.cdn,
    "cityNames": [
      "杭州市",
      "宁波市",
      "温州市",
      "嘉兴市",
      "湖州市",
      "绍兴市",
      "金华市",
      "衢州市",
      "舟山市",
      "台州市",
      "丽水市"
    ],
    cityPinyin: [
      "hangzhoushi",
      "ningboshi",
      "wenzhoushi",
      "jiaxingshi",
      "huzhoushi",
      "shaoxingshi",
      "jinhuashi",
      "quzhoushi",
      "zhoushanshi",
      "taizhoushi",
      "lishuishi"
    ],
    "cities": {
      "温州": "温州市",
      "杭州": "杭州市",
      "台州": "台州市",
      "宁波": "宁波市",
      "金华": "金华市",
      "绍兴": "绍兴市",
      "嘉兴": "嘉兴市",
      "衢州": "衢州市",
      "丽水": "丽水市",
      "舟山": "舟山市",
      "湖州": "湖州市"
    },
    "center": [
      120.153576,
      30.287459
    ]
  }
]